### ISSUE TITLE
Build error in build.gradle while first time set up 

### ISSUE THREAD

**Issue by shailendrasinghtomar** [MarcusNg/flutter_instagram_clone#1]
I am new learner for flutter + firebase, got this nice tutorial on youtube. 
i am setting it up on my machine. It giving me below build error, code is exactly same as in repo.
just ran 
get package and flutter doctor which is fine with no issue. still giving this build error.  

**Debug output**  -
--------------------
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
*Error running Gradle:
ProcessException: Process "C:\MobileApp\Example\flutter_instagram_clone-master\flutter_instagram_clone-master\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

*Where:
Build file 'C:\MobileApp\Example\flutter_instagram_clone-master\flutter_instagram_clone-master\android\app\build.gradle' line: 24

*What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

*Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\MobileApp\Example\flutter_instagram_clone-master\flutter_instagram_clone-master\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

```

**Comment by MarcusNg** [comment]
The app runs fine for me on Android. Try reinstalling the Flutter and Dart plugins on Android Studio.

**Comment by shailendrasinghtomar** [comment]
I have to change the classpath 'com.google.gms:google-services:4.2.0' in gradle.build file, then its work fine. thanks it was nice tutorial for me.

**Comment by Giyomeh** [comment]
Can you post the content of your Flutter doctor - your solution is not working for me, and I would love to compare your environment.
Thanks
