### ISSUE TITLE
Hi Marcus One Question.

### ISSUE THREAD

**Issue by Isonomic** [MarcusNg/flutter_instagram_clone#2]
Anytime I Signup it works creating an account in firebase but takes me back to the android screen. Same with login, it goes to this screen. Any idea why? My code is the same as yours other then my firebase creds. Please and thank you. It takes me back to this screen

**Comment by Isonomic** [comment]
![Screenshot (127)](https://user-images.githubusercontent.com/37713396/69105992-3efe9f80-0a2a-11ea-9b6e-6ad2a74f51ea.png)

**Comment by MarcusNg** [comment]
When you say it takes you back to the android screen, do you mean the app crashes? If so, what is the error message?

**Comment by Isonomic** [comment]
yes it does Marcus. PS thank you so much. You are my new favorite teacher for flutter. I love your course and you know your stuff I can tell. And thank you for responding. There are no other issues so I am sure its just me. I will show you what it says. I am thinking its on Firebase end maybe. I will send it. Once again you freaking rock man. What do you do for work? Are you unbusy enought to partner on a flutter app if I pay you ?

**Comment by Isonomic** [comment]
Here it is Marcus. Let me know about the work too bro ok. If you need money and have time, I got you covered. 
![Screenshot (136)](https://user-images.githubusercontent.com/37713396/69248417-817ac600-0b69-11ea-8a83-e6c997576fbd.png)
![Screenshot (137)](https://user-images.githubusercontent.com/37713396/69248418-817ac600-0b69-11ea-8c3e-826eb2d73c1d.png)
![Screenshot (134)](https://user-images.githubusercontent.com/37713396/69248431-863f7a00-0b69-11ea-8b6f-749887d178c4.png)

**Comment by Isonomic** [comment]
And then I will close this issue and remove it. I really appreciatte this help and cant seem to figure out what is wrong with what I am doing. I copy and pasted your latest code from github on episode 8

**Comment by MarcusNg** [comment]
Thanks for your kind words! I'm tied up with multiple projects right now, so I'm too busy to partner at the moment :(
I think it has to do with either the way you are navigating to the next screen or handling errors. Do you have a GitHub repo I can take a look at?

**Comment by Isonomic** [comment]
Holy crap man, I got it working. The only reason I can think of is the gradle.properties with that jettifer enable true. I will close this issue

**Comment by MarcusNg** [comment]
Awesome! :)

**Comment by Isonomic** [comment]
Dude I got it. Your the best though man. Dont worry. Mad respect. Are you going to be doing more flutter firestore stuff? I will take this down now. Shouted you out on youtube on your last video too. How can I guy ever message you if he has something really huge for you ? Just open an issue lol???

**Comment by Isonomic** [comment]
One last thing, when you say other projects, do you mean feeelance for people? Just curious as to what you do for work or to make money. And after that, take care my firend. Keep that full app stuff coming. the community loves real world working projects with backends. Chow man. Will remove this issue after you respond

**Comment by MarcusNg** [comment]
Thanks for the shoutout! You can contact me at marcusngdev@gmail.com
I do freelance, and I'm always open to new projects. Just contact me via email :)
